name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to bump?'
        required: true
        type: choice
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  verify:
    uses: jonmckee/actions/.github/workflows/verify.yml@main

  publish:
    needs: verify
    uses: jonmckee/actions/.github/workflows/publish.yml@main
    with:
      version: ${{ inputs.version }}
