name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Which version to bump?'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run coverage

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'jonrmckee@gmail.com'
      - run: npm version ${{github.event.inputs.version}}
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
